version: '2'
services:
    daspanel-storage:
        image: daspanel/minio-fileserver
        volumes:
            - ./data:/opt/daspanel/data
        networks:
            - backend
        expose:
            - "9000"
        env_file:
            - daspanel.env
    daspanel-services:
        image: daspanel/daspanel-services
        volumes:
            - /opt/daspanel/services
        networks:
            - backend
        command:
            - /bin/true
        depends_on:
            - daspanel-storage
    daspanel-mail-catcher:
        image: daspanel/mailhog-mail-catcher
        volumes:
            - ./data:/opt/daspanel/data
        networks:
            - frontend
            - backend
        env_file:
            - daspanel.env
        depends_on:
            - daspanel-storage
    daspanel-mysql:
        image: daspanel/mariadb
        volumes:
            - ./data:/opt/daspanel/data
        networks:
            backend:
                aliases:
                    - daspanel-mariadb
        expose:
            - "3306"
        environment:
            - MARIADB_REMOTE_ROOT=true
        env_file:
            - daspanel.env
        depends_on:
            - daspanel-storage
    daspanel-php-fpm-5.6:
        image: daspanel/php-fpm-5.6
        volumes:
            - ./data:/opt/daspanel/data
        networks:
            - backend
        expose:
            - "9000"
        env_file:
            - daspanel.env
        depends_on:
            - daspanel-storage
    daspanel-php-fpm-7.0:
        image: daspanel/php-fpm-7.0
        volumes:
            - ./data:/opt/daspanel/data
        volumes_from:
            - daspanel-services:ro
        networks:
            - backend
        expose:
            - "9000"
        env_file:
            - daspanel.env
        depends_on:
            - daspanel-storage
    daspanel-http-server:
        image: daspanel/caddy-http-server
        volumes:
            - ./data:/opt/daspanel/data
        volumes_from:
            - daspanel-services:ro
        networks:
            - frontend
            - backend
        ports:
            - "80:80"
            - "443:443"
        env_file:
            - daspanel.env
        depends_on:
            - daspanel-storage
    daspanel-api:
        image: daspanel/api-server:latest
        volumes:
            - ./data:/opt/daspanel/data
        networks:
            - frontend
            - backend
        environment:
            - GUNICORN_APP_DIR=/opt/daspanel/apps/apiserver/api_server
            - GUNICORN_CMD=/opt/daspanel/apps/apiserver/api_server/wsgi_gunicorn --bind=0.0.0.0:8080 --user=daspanel --group=daspanel api-connexion:app Daspanel_Api_Server
        env_file:
            - daspanel.env
        expose:
            - "5000"
            - "8080"
        depends_on:
            - daspanel-mail-catcher
            - daspanel-mysql
    daspanel-panel:
        image: daspanel/panel:latest
        volumes:
            - ./data:/opt/daspanel/data
        networks:
            - frontend
            - backend
        environment:
            - GUNICORN_APP_DIR=/opt/daspanel/apps/panel/daspanel_web
            - GUNICORN_CMD=su-exec daspanel:daspanel python /opt/daspanel/apps/panel/wsgi.py
        env_file:
            - daspanel.env
        expose:
            - "5000"
        depends_on:
            - daspanel-api
networks:  
  frontend:
    driver: bridge
  backend:
    driver: bridge


